import { useState } from 'react'
import { Plus, FolderOpen, Search, ArrowRight } from 'lucide-react'
import { AdminThemeButton } from '@/components/AdminThemeButton'
import { Button } from '@/components/ui/Button/Button'
import { Input } from '@/components/ui/Input/Input'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/Select/Select'
import { Switch } from '@/components/ui/Switch/Switch'
import { Modal, ModalTitle, ModalDescription, ModalHeader, ModalContent, ModalFooter, ModalCloseButton } from '@/components/ui/Modal/Modal'
import { Badge } from '@/components/ui/Badge/Badge'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/shadcn/card'
import { MetricSummary } from '@/components/ui/MetricSummary'
import { accentFor } from './dashboard/colors'
import { CountChart } from '@/components/ui/CountChart'
import { Checkbox } from '@/components/ui/shadcn/checkbox'
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from '@/components/ui/shadcn/table'
const ramp=[50,100,200,300,400,500,600,700,800,900,950]
const hex=['#F7FCE8','#EDF7C2','#DDEF8B','#CDE45A','#C3D82E','#A6BC1B','#809213','#5E6C16','#49541A','#3C451B','#1D2409']
export default function DesignSystem(){
 const [project,setProject]=useState(''); const [enabled,setEnabled]=useState(true); const [open,setOpen]=useState(false)
 return <div className="min-h-dvh bg-background text-foreground px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl space-y-8">
 <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">NexusMind · Audit1 Lima</h1><p className="mt-2 text-sm text-muted-foreground">Paleta y componentes. Vista de desarrollo con datos de ejemplo.</p></div><AdminThemeButton/></header>
 <section className="space-y-4" aria-labelledby="palette-heading"><h2 id="palette-heading" className="text-lg font-semibold">Primero, la paleta</h2><div className="grid grid-cols-3 gap-3 sm:grid-cols-6 xl:grid-cols-11">{ramp.map((shade,i)=><div key={shade}><div className="h-20 rounded-md border" style={{background:`var(--lime-${shade})`}}/><p className="mt-2 text-sm font-medium">{shade}{shade===400?' · Marca':''}</p><code className="text-xs text-muted-foreground">{hex[i]}</code></div>)}</div><p className="max-w-3xl text-sm text-muted-foreground">Superficies blancas y negras de Audit1. Lima 400 para acciones, 950 para su texto y 700 para enlaces sobre blanco. Los estados conservan sus colores semánticos.</p></section>
 <div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Acciones y estados</CardTitle><CardDescription>Altura estándar de 36 px, radios de 8 px y foco visible.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="flex flex-wrap gap-2"><Button leftIcon={<Plus/>} onClick={()=>setOpen(true)}>Nuevo proyecto</Button><Button variant="outline">Exportar</Button><Button variant="secondary">Opciones</Button><Button variant="ghost">Cancelar</Button></div><div className="flex flex-wrap gap-2"><Button disabled>Deshabilitado</Button><Button loading aria-label="Guardando">Guardando</Button><Button variant="destructive">Eliminar</Button></div><div className="flex flex-wrap gap-2"><Badge>Neutral</Badge><Badge variant="success">Activo</Badge><Badge variant="warning">Pendiente</Badge><Badge variant="error">Error</Badge><Badge variant="info">Información</Badge></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Formulario</CardTitle><CardDescription>Controles compartidos por las pantallas del admin.</CardDescription></CardHeader><CardContent className="space-y-4"><Input label="Nombre del proyecto" placeholder="Mi proyecto"/><Input label="Buscar" leftIcon={<Search/>} placeholder="Buscar memorias…"/><div className="space-y-1.5"><label htmlFor="palette-project" className="text-sm font-medium">Proyecto</label><Select value={project} onValueChange={setProject}><SelectTrigger id="palette-project" className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="">Todos los proyectos</SelectItem><SelectItem value="demo">Proyecto de ejemplo</SelectItem></SelectContent></Select></div><Switch checked={enabled} onCheckedChange={setEnabled} label="Notificaciones" description="Recibir novedades del proyecto."/><Input label="Campo con error" defaultValue="" error="Escribe un nombre para continuar."/></CardContent></Card></div>
 <section className="space-y-4" aria-label="Contadores y gráficas de ejemplo"><h2 className="text-lg font-semibold">Contadores compactos</h2><div className="flex flex-wrap items-start gap-2">{[['Memorias','1,284'],['Proyectos','12'],['Miembros','8']].map(([label,value],i)=><MetricSummary key={label} label={label} value={value} icon={FolderOpen} accent={accentFor(i)}><p>Contexto visible · Datos de ejemplo</p></MetricSummary>)}</div><Card><CardHeader><CardTitle>Gráficas shadcn</CardTitle><CardDescription>Datos de ejemplo. Ejes, tooltip y colores compartidos en claro y oscuro.</CardDescription></CardHeader><CardContent><CountChart label="Memorias de ejemplo" data={[{name:'API de ejemplo',count:642},{name:'Documentación',count:328},{name:'Aplicación web',count:314}]} /></CardContent></Card></section>
 <Card className="gap-4"><CardHeader><CardTitle>Proyectos</CardTitle><CardDescription>Tabla de ejemplo con selección y acciones.</CardDescription></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead className="w-10"><Checkbox aria-label="Seleccionar todos los ejemplos"/></TableHead><TableHead>Nombre</TableHead><TableHead>Estado</TableHead><TableHead className="text-right">Memorias</TableHead><TableHead><span className="sr-only">Acciones</span></TableHead></TableRow></TableHeader><TableBody>{['API de ejemplo','Documentación','Aplicación web'].map((label,i)=><TableRow key={label}><TableCell><Checkbox aria-label={`Seleccionar ${label}`}/></TableCell><TableCell className="font-medium">{label}</TableCell><TableCell><Badge variant={i===1?'warning':'success'}>{i===1?'Pendiente':'Activo'}</Badge></TableCell><TableCell className="text-right tabular-nums">{[642,328,314][i]}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" aria-label={`Ver ${label}`} onClick={()=>setOpen(true)}><ArrowRight className="size-4"/></Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
 <Modal open={open} onOpenChange={setOpen}><ModalCloseButton/><ModalHeader><ModalTitle>Nuevo proyecto</ModalTitle><ModalDescription>Ejemplo del diálogo de Audit1 con la paleta lima.</ModalDescription></ModalHeader><ModalContent><Input label="Nombre" placeholder="Nombre del proyecto"/></ModalContent><ModalFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={()=>setOpen(false)}>Cerrar ejemplo</Button></ModalFooter></Modal>
 </div></div>
}
